#!/usr/bin/env python3
"""Add Settings and Calculator mode handlers to kernel_v2.arnoldc"""
import os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))

f = open('kernel/kernel_v2.arnoldc', 'r')
content = f.read()
f.close()

marker = '                TALK TO YOURSELF "Check if we are in menu mode (use modeAtFrameStart to prevent fall-through)"'
idx = content.find(marker)
if idx == -1:
    print('ERROR: marker not found')
    sys.exit(1)

L = []
def a(s): L.append(s)
IM = "I'M"

# === SETTINGS MODE ===
a(f'                TALK TO YOURSELF "=== SETTINGS MODE INPUT ==="')
a( '                HEY CHRISTMAS TREE isSettingsMode')
a( '                THIS IS A WARRIOR')
a( '                YOU SET US UP 0')
a( '                GET TO THE CHOPPER isSettingsMode')
a( '                HERE IS MY INVITATION currentMode')
a( '                YOU ARE NOT YOU YOU ARE ME MODE_SETTINGS')
a( '                ENOUGH TALK')
a(f'                BECAUSE {IM} GOING TO SAY PLEASE isSettingsMode')
a( '                    TALK TO YOURSELF "Settings: Up/Down, Enter toggle, ESC"')

for nm, sc, cmp, cv, op in [
    ('isSettUp', 72, 'LET OFF SOME STEAM BENNET', 0, 'GET DOWN'),
    ('isSettDn', 80, "YOU'RE NOT BIG ENOUGH", 2, 'GET UP'),
]:
    a(f'                    HEY CHRISTMAS TREE {nm}')
    a( '                    THIS IS A WARRIOR')
    a( '                    YOU SET US UP 0')
    a(f'                    GET TO THE CHOPPER {nm}')
    a( '                    HERE IS MY INVITATION scancode')
    a(f'                    YOU ARE NOT YOU YOU ARE ME {sc}')
    a( '                    ENOUGH TALK')
    a(f'                    BECAUSE {IM} GOING TO SAY PLEASE {nm}')
    a(f'                        HEY CHRISTMAS TREE can{nm}')
    a( '                        THIS IS A WARRIOR')
    a( '                        YOU SET US UP 0')
    a(f'                        GET TO THE CHOPPER can{nm}')
    a( '                        HERE IS MY INVITATION settingsSelected')
    a(f'                        {cmp} {cv}')
    a( '                        ENOUGH TALK')
    a(f'                        BECAUSE {IM} GOING TO SAY PLEASE can{nm}')
    a( '                            GET TO THE CHOPPER settingsSelected')
    a( '                            HERE IS MY INVITATION settingsSelected')
    a(f'                            {op} 1')
    a( '                            ENOUGH TALK')
    a( '                        YOU HAVE NO RESPECT FOR LOGIC')
    a( '                    YOU HAVE NO RESPECT FOR LOGIC')

a( '                    HEY CHRISTMAS TREE isSettEnt')
a( '                    THIS IS A WARRIOR')
a( '                    YOU SET US UP 0')
a( '                    GET TO THE CHOPPER isSettEnt')
a( '                    HERE IS MY INVITATION scancode')
a( '                    YOU ARE NOT YOU YOU ARE ME 28')
a( '                    ENOUGH TALK')
a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isSettEnt')
a( '                        HEY CHRISTMAS TREE isSSnd')
a( '                        THIS IS A WARRIOR')
a( '                        YOU SET US UP 0')
a( '                        GET TO THE CHOPPER isSSnd')
a( '                        HERE IS MY INVITATION settingsSelected')
a( '                        YOU ARE NOT YOU YOU ARE ME 0')
a( '                        ENOUGH TALK')
a(f'                        BECAUSE {IM} GOING TO SAY PLEASE isSSnd')
a( '                            HEY CHRISTMAS TREE sndNow')
a( '                            THIS IS A WARRIOR')
a( '                            YOU SET US UP 0')
a( '                            GET TO THE CHOPPER sndNow')
a( '                            HERE IS MY INVITATION soundEnabled')
a( '                            YOU ARE NOT YOU YOU ARE ME 1')
a( '                            ENOUGH TALK')
a(f'                            BECAUSE {IM} GOING TO SAY PLEASE sndNow')
a( '                                GET TO THE CHOPPER soundEnabled')
a( '                                HERE IS MY INVITATION 0')
a( '                                ENOUGH TALK')
a( '                            BULLSHIT')
a( '                                GET TO THE CHOPPER soundEnabled')
a( '                                HERE IS MY INVITATION 1')
a( '                                ENOUGH TALK')
a( '                            YOU HAVE NO RESPECT FOR LOGIC')
a( '                        YOU HAVE NO RESPECT FOR LOGIC')
a( '                        HEY CHRISTMAS TREE isSSpd')
a( '                        THIS IS A WARRIOR')
a( '                        YOU SET US UP 0')
a( '                        GET TO THE CHOPPER isSSpd')
a( '                        HERE IS MY INVITATION settingsSelected')
a( '                        YOU ARE NOT YOU YOU ARE ME 1')
a( '                        ENOUGH TALK')
a(f'                        BECAUSE {IM} GOING TO SAY PLEASE isSSpd')
a( '                            GET TO THE CHOPPER gameSpeedSetting')
a( '                            HERE IS MY INVITATION gameSpeedSetting')
a( '                            GET UP 1')
a( '                            ENOUGH TALK')
a( '                            HEY CHRISTMAS TREE sWrap')
a( '                            THIS IS A WARRIOR')
a( '                            YOU SET US UP 0')
a( '                            GET TO THE CHOPPER sWrap')
a( '                            HERE IS MY INVITATION gameSpeedSetting')
a( '                            LET OFF SOME STEAM BENNET 2')
a( '                            ENOUGH TALK')
a(f'                            BECAUSE {IM} GOING TO SAY PLEASE sWrap')
a( '                                GET TO THE CHOPPER gameSpeedSetting')
a( '                                HERE IS MY INVITATION 0')
a( '                                ENOUGH TALK')
a( '                            YOU HAVE NO RESPECT FOR LOGIC')
a( '                        YOU HAVE NO RESPECT FOR LOGIC')
a( '                    YOU HAVE NO RESPECT FOR LOGIC')

a( '                    HEY CHRISTMAS TREE isEscSet')
a( '                    THIS IS A WARRIOR')
a( '                    YOU SET US UP 0')
a( '                    GET TO THE CHOPPER isEscSet')
a( '                    HERE IS MY INVITATION scancode')
a( '                    YOU ARE NOT YOU YOU ARE ME 1')
a( '                    ENOUGH TALK')
a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isEscSet')
a( '                        GET TO THE CHOPPER currentMode')
a( '                        HERE IS MY INVITATION MODE_MENU')
a( '                        ENOUGH TALK')
a( '                        DO IT NOW redrawMenu fbAddress fbPitch')
a( '                    YOU HAVE NO RESPECT FOR LOGIC')

a( '                    DO IT NOW clearScreen fbAddress fbPitch fbWidth fbHeight COLOR_DARK_BLUE')
a( '                    DO IT NOW drawStringAt fbAddress fbPitch 400 40 menuOpt9 12 COLOR_WHITE COLOR_DARK_BLUE')

for i, col in enumerate(['sC0', 'sC1', 'sC2']):
    a(f'                    HEY CHRISTMAS TREE {col}')
    a( '                    THIS IS A WARRIOR')
    a( '                    YOU SET US UP 0')
    a(f'                    GET TO THE CHOPPER {col}')
    a( '                    HERE IS MY INVITATION COLOR_WHITE')
    a( '                    ENOUGH TALK')
    a(f'                    HEY CHRISTMAS TREE isHL{i}')
    a( '                    THIS IS A WARRIOR')
    a( '                    YOU SET US UP 0')
    a(f'                    GET TO THE CHOPPER isHL{i}')
    a( '                    HERE IS MY INVITATION settingsSelected')
    a(f'                    YOU ARE NOT YOU YOU ARE ME {i}')
    a( '                    ENOUGH TALK')
    a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isHL{i}')
    a(f'                        GET TO THE CHOPPER {col}')
    a( '                        HERE IS MY INVITATION COLOR_YELLOW')
    a( '                        ENOUGH TALK')
    a( '                    YOU HAVE NO RESPECT FOR LOGIC')

# Sound row: "SOUND: ON" or "SOUND: OFF" drawn char by char
a( '                    DO IT NOW fillRect fbAddress fbPitch 300 100 400 30 COLOR_DARK_BLUE')
a( '                    HEY CHRISTMAS TREE sSndD')
a( '                    THIS IS A WARRIOR')
a( '                    YOU SET US UP 0')
a( '                    GET TO THE CHOPPER sSndD')
a( '                    HERE IS MY INVITATION soundEnabled')
a( '                    YOU ARE NOT YOU YOU ARE ME 1')
a( '                    ENOUGH TALK')
a(f'                    BECAUSE {IM} GOING TO SAY PLEASE sSndD')
for i, ch in enumerate([0x3E,0x20,0x53,0x4F,0x55,0x4E,0x44,0x3A,0x20,0x4F,0x4E]):
    a(f'                        DO IT NOW drawChar fbAddress fbPitch {330+i*10} 107 {hex(ch)} sC0 COLOR_DARK_BLUE')
a( '                    BULLSHIT')
for i, ch in enumerate([0x3E,0x20,0x53,0x4F,0x55,0x4E,0x44,0x3A,0x20,0x4F,0x46,0x46]):
    a(f'                        DO IT NOW drawChar fbAddress fbPitch {330+i*10} 107 {hex(ch)} sC0 COLOR_DARK_BLUE')
a( '                    YOU HAVE NO RESPECT FOR LOGIC')

# Speed row: "SPEED: 0/1/2"
a( '                    DO IT NOW fillRect fbAddress fbPitch 300 140 400 30 COLOR_DARK_BLUE')
for i, ch in enumerate([0x3E,0x20,0x53,0x50,0x45,0x45,0x44,0x3A]):
    a(f'                    DO IT NOW drawChar fbAddress fbPitch {330+i*10} 147 {hex(ch)} sC1 COLOR_DARK_BLUE')
a( '                    DO IT NOW drawNumber fbAddress fbPitch 420 147 gameSpeedSetting sC1 COLOR_DARK_BLUE')

# About row
a( '                    DO IT NOW fillRect fbAddress fbPitch 300 180 400 30 COLOR_DARK_BLUE')
for i, ch in enumerate([0x3E,0x20,0x41,0x42,0x4F,0x55,0x54]):
    a(f'                    DO IT NOW drawChar fbAddress fbPitch {330+i*10} 187 {hex(ch)} sC2 COLOR_DARK_BLUE')
a( '                YOU HAVE NO RESPECT FOR LOGIC')
a( '')

# === CALCULATOR MODE ===
a( '                TALK TO YOURSELF "=== CALCULATOR MODE INPUT ==="')
a( '                HEY CHRISTMAS TREE isCalcMode')
a( '                THIS IS A WARRIOR')
a( '                YOU SET US UP 0')
a( '                GET TO THE CHOPPER isCalcMode')
a( '                HERE IS MY INVITATION currentMode')
a( '                YOU ARE NOT YOU YOU ARE ME MODE_CALC')
a( '                ENOUGH TALK')
a(f'                BECAUSE {IM} GOING TO SAY PLEASE isCalcMode')

a( '                    HEY CHRISTMAS TREE isCEsc')
a( '                    THIS IS A WARRIOR')
a( '                    YOU SET US UP 0')
a( '                    GET TO THE CHOPPER isCEsc')
a( '                    HERE IS MY INVITATION scancode')
a( '                    YOU ARE NOT YOU YOU ARE ME 1')
a( '                    ENOUGH TALK')
a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isCEsc')
a( '                        GET TO THE CHOPPER currentMode')
a( '                        HERE IS MY INVITATION MODE_MENU')
a( '                        ENOUGH TALK')
a( '                        DO IT NOW redrawMenu fbAddress fbPitch')
a( '                    YOU HAVE NO RESPECT FOR LOGIC')

for d in range(10):
    sc = 11 if d == 0 else d + 1
    a(f'                    HEY CHRISTMAS TREE isK{d}')
    a( '                    THIS IS A WARRIOR')
    a( '                    YOU SET US UP 0')
    a(f'                    GET TO THE CHOPPER isK{d}')
    a( '                    HERE IS MY INVITATION scancode')
    a(f'                    YOU ARE NOT YOU YOU ARE ME {sc}')
    a( '                    ENOUGH TALK')
    a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isK{d}')
    a(f'                        HEY CHRISTMAS TREE isNI{d}')
    a( '                        THIS IS A WARRIOR')
    a( '                        YOU SET US UP 0')
    a(f'                        GET TO THE CHOPPER isNI{d}')
    a( '                        HERE IS MY INVITATION calcNewInput')
    a( '                        YOU ARE NOT YOU YOU ARE ME 1')
    a( '                        ENOUGH TALK')
    a(f'                        BECAUSE {IM} GOING TO SAY PLEASE isNI{d}')
    a( '                            GET TO THE CHOPPER calcDisplay')
    a( '                            HERE IS MY INVITATION 0')
    a( '                            ENOUGH TALK')
    a( '                            GET TO THE CHOPPER calcNewInput')
    a( '                            HERE IS MY INVITATION 0')
    a( '                            ENOUGH TALK')
    a( '                        YOU HAVE NO RESPECT FOR LOGIC')
    a( '                        GET TO THE CHOPPER calcDisplay')
    a( '                        HERE IS MY INVITATION calcDisplay')
    a( '                        HE HAD TO SPLIT 10')
    a(f'                        GET UP {d}')
    a( '                        ENOUGH TALK')
    a( '                    YOU HAVE NO RESPECT FOR LOGIC')

for nm, sc, op in [('CPlus', 78, 1), ('CMinus', 74, 2), ('CMul', 55, 3)]:
    a(f'                    HEY CHRISTMAS TREE is{nm}')
    a( '                    THIS IS A WARRIOR')
    a( '                    YOU SET US UP 0')
    a(f'                    GET TO THE CHOPPER is{nm}')
    a( '                    HERE IS MY INVITATION scancode')
    a(f'                    YOU ARE NOT YOU YOU ARE ME {sc}')
    a( '                    ENOUGH TALK')
    a(f'                    BECAUSE {IM} GOING TO SAY PLEASE is{nm}')
    a( '                        GET TO THE CHOPPER calcOperand')
    a( '                        HERE IS MY INVITATION calcDisplay')
    a( '                        ENOUGH TALK')
    a( '                        GET TO THE CHOPPER calcOperator')
    a(f'                        HERE IS MY INVITATION {op}')
    a( '                        ENOUGH TALK')
    a( '                        GET TO THE CHOPPER calcNewInput')
    a( '                        HERE IS MY INVITATION 1')
    a( '                        ENOUGH TALK')
    a( '                    YOU HAVE NO RESPECT FOR LOGIC')

a( '                    HEY CHRISTMAS TREE isCEq')
a( '                    THIS IS A WARRIOR')
a( '                    YOU SET US UP 0')
a( '                    GET TO THE CHOPPER isCEq')
a( '                    HERE IS MY INVITATION scancode')
a( '                    YOU ARE NOT YOU YOU ARE ME 28')
a( '                    ENOUGH TALK')
a(f'                    BECAUSE {IM} GOING TO SAY PLEASE isCEq')
for nm, v, arnop in [('CAdd', 1, 'GET UP'), ('CSub', 2, 'GET DOWN'), ('CMl2', 3, 'HE HAD TO SPLIT')]:
    a(f'                        HEY CHRISTMAS TREE is{nm}')
    a( '                        THIS IS A WARRIOR')
    a( '                        YOU SET US UP 0')
    a(f'                        GET TO THE CHOPPER is{nm}')
    a( '                        HERE IS MY INVITATION calcOperator')
    a(f'                        YOU ARE NOT YOU YOU ARE ME {v}')
    a( '                        ENOUGH TALK')
    a(f'                        BECAUSE {IM} GOING TO SAY PLEASE is{nm}')
    a( '                            GET TO THE CHOPPER calcDisplay')
    a( '                            HERE IS MY INVITATION calcOperand')
    a(f'                            {arnop} calcDisplay')
    a( '                            ENOUGH TALK')
    a( '                        YOU HAVE NO RESPECT FOR LOGIC')
a( '                        GET TO THE CHOPPER calcOperator')
a( '                        HERE IS MY INVITATION 0')
a( '                        ENOUGH TALK')
a( '                        GET TO THE CHOPPER calcNewInput')
a( '                        HERE IS MY INVITATION 1')
a( '                        ENOUGH TALK')
a( '                    YOU HAVE NO RESPECT FOR LOGIC')

a( '                    DO IT NOW clearScreen fbAddress fbPitch fbWidth fbHeight COLOR_DARK_BLUE')
a( '                    DO IT NOW fillRect fbAddress fbPitch 312 100 400 350 COLOR_WIN95_GRAY')
a( '                    DO IT NOW fillRect fbAddress fbPitch 312 100 400 2 COLOR_WHITE')
a( '                    DO IT NOW fillRect fbAddress fbPitch 312 100 2 350 COLOR_WHITE')
a( '                    DO IT NOW fillRect fbAddress fbPitch 312 448 400 2 COLOR_WIN95_SHADOW')
a( '                    DO IT NOW fillRect fbAddress fbPitch 710 100 2 350 COLOR_WIN95_SHADOW')
a( '                    DO IT NOW drawStringAt fbAddress fbPitch 450 110 menuOpt11 8 COLOR_BLACK COLOR_WIN95_GRAY')
a( '                    DO IT NOW fillRect fbAddress fbPitch 332 140 360 50 COLOR_BLACK')
a( '                    DO IT NOW drawNumber fbAddress fbPitch 340 155 calcDisplay COLOR_GREEN COLOR_BLACK')

for bx, by, ch in [
    (332,210,0x37),(422,210,0x38),(512,210,0x39),
    (332,270,0x34),(422,270,0x35),(512,270,0x36),
    (332,330,0x31),(422,330,0x32),(512,330,0x33),
    (332,390,0x30),
]:
    a(f'                    DO IT NOW fillRect fbAddress fbPitch {bx} {by} 80 50 COLOR_WIN95_GRAY')
    a(f'                    DO IT NOW drawChar fbAddress fbPitch {bx+30} {by+15} {hex(ch)} COLOR_BLACK COLOR_WIN95_GRAY')

for ox, oy, ch, col in [
    (602,210,0x2B,'COLOR_ARNOLD_RED'),
    (602,270,0x2D,'COLOR_ARNOLD_RED'),
    (602,330,0x2A,'COLOR_ARNOLD_RED'),
    (602,390,0x3D,'COLOR_GREEN'),
]:
    a(f'                    DO IT NOW fillRect fbAddress fbPitch {ox} {oy} 80 50 {col}')
    a(f'                    DO IT NOW drawChar fbAddress fbPitch {ox+30} {oy+15} {hex(ch)} COLOR_WHITE {col}')

a( '                YOU HAVE NO RESPECT FOR LOGIC')
a( '')

insert = '\n'.join(L) + '\n'
content = content[:idx] + insert + content[idx:]
f = open('kernel/kernel_v2.arnoldc', 'w')
f.write(content)
f.close()
print(f'Added {len(L)} lines of Settings + Calculator handlers')
