cols=80
rows=25
size=cols*rows
vals=['0x20']*size
lines=[' '.join(vals[i:i+16]) for i in range(0,size,16)]
buffer='\n'.join(lines)

mapping = {
    0x1E:'0x61',0x30:'0x62',0x2E:'0x63',0x20:'0x64',0x12:'0x65',0x21:'0x66',0x22:'0x67',0x23:'0x68',
    0x17:'0x69',0x24:'0x6A',0x25:'0x6B',0x26:'0x6C',0x32:'0x6D',0x31:'0x6E',0x18:'0x6F',
    0x19:'0x70',0x10:'0x71',0x13:'0x72',0x1F:'0x73',0x14:'0x74',0x16:'0x75',0x2F:'0x76',
    0x11:'0x77',0x2D:'0x78',0x15:'0x79',0x2C:'0x7A',
    0x02:'0x31',0x03:'0x32',0x04:'0x33',0x05:'0x34',0x06:'0x35',0x07:'0x36',0x08:'0x37',
    0x09:'0x38',0x0A:'0x39',0x0B:'0x30',
    0x39:'0x20'
}

map_lines = []
map_lines.append('HEY CHRISTMAS TREE isMatch')
map_lines.append('THIS IS A WARRIOR')
map_lines.append('YOU SET US UP 0')
for sc, asc in mapping.items():
    map_lines.append('GET TO THE CHOPPER isMatch')
    map_lines.append('HERE IS MY INVITATION scancode')
    map_lines.append(f'YOU ARE NOT YOU YOU ARE ME 0x{sc:02X}')
    map_lines.append('ENOUGH TALK')
    map_lines.append('BECAUSE I\'M GOING TO SAY PLEASE isMatch')
    map_lines.append('    GET TO THE CHOPPER ascii')
    map_lines.append(f'    HERE IS MY INVITATION {asc}')
    map_lines.append('    ENOUGH TALK')
    map_lines.append('    GET TO THE CHOPPER isMapped')
    map_lines.append('    HERE IS MY INVITATION 1')
    map_lines.append('    ENOUGH TALK')
    map_lines.append('YOU HAVE NO RESPECT FOR LOGIC')
map_lines.append('HEY CHRISTMAS TREE shouldPut')
map_lines.append('THIS IS A WARRIOR')
map_lines.append('YOU SET US UP 0')
map_lines.append('GET TO THE CHOPPER shouldPut')
map_lines.append('HERE IS MY INVITATION isMapped')
map_lines.append('YOU ARE NOT YOU YOU ARE ME 1')
map_lines.append('ENOUGH TALK')
map_lines.append('BECAUSE I\'M GOING TO SAY PLEASE shouldPut')
map_lines.append('    DO IT NOW termPutChar ascii')
map_lines.append('YOU HAVE NO RESPECT FOR LOGIC')
map_block='\n'.join(map_lines)

content=f'''TALK TO YOURSELF "============================================================================"
TALK TO YOURSELF "  TERMINAL MODULE"
TALK TO YOURSELF "============================================================================"

TALK TO YOURSELF "Terminal constants"
LET ME TELL YOU SOMETHING TERM_COLS {cols}
LET ME TELL YOU SOMETHING TERM_ROWS {rows}
LET ME TELL YOU SOMETHING TERM_SIZE {size}
LET ME TELL YOU SOMETHING CHAR_W 8
LET ME TELL YOU SOMETHING CHAR_H 16
LET ME TELL YOU SOMETHING TERM_WIDTH_PX 1024
LET ME TELL YOU SOMETHING TERM_BG 0x00000000
LET ME TELL YOU SOMETHING TERM_FG 0x0000FF00

TALK TO YOURSELF "Terminal state"
HEY CHRISTMAS TREE termBuffer
LINE THEM UP
THIS IS A TINY WARRIOR
HOW MANY {size}
PUT THEM IN LINE
{buffer}

HEY CHRISTMAS TREE cursorX
THIS IS A WARRIOR
YOU SET US UP 0

HEY CHRISTMAS TREE cursorY
THIS IS A WARRIOR
YOU SET US UP 0

HEY CHRISTMAS TREE scrollOffset
THIS IS A WARRIOR
YOU SET US UP 0

HEY CHRISTMAS TREE dirtyLine
THIS IS A WARRIOR
YOU SET US UP -2

HEY CHRISTMAS TREE cursorBlink
THIS IS A WARRIOR
YOU SET US UP 1

TALK TO YOURSELF "============================================================================"
TALK TO YOURSELF "  TERMINAL HELPERS"
TALK TO YOURSELF "============================================================================"

LISTEN TO ME VERY CAREFULLY termClearLine
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE lineIndex
HEY CHRISTMAS TREE i
THIS IS A WARRIOR
YOU SET US UP 0
HEY CHRISTMAS TREE base
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER base
HERE IS MY INVITATION lineIndex
YOU'RE FIRED TERM_COLS
ENOUGH TALK
STICK AROUND i
    HEY CHRISTMAS TREE idx
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER idx
    HERE IS MY INVITATION base
    GET UP i
    ENOUGH TALK
    GET TO THE CHOPPER WHICH ONE termBuffer idx
    HERE IS MY INVITATION 0x20
    ENOUGH TALK
    GET TO THE CHOPPER i
    HERE IS MY INVITATION i
    GET UP 1
    ENOUGH TALK
    HEY CHRISTMAS TREE done
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER done
    HERE IS MY INVITATION i
    YOU'RE AT LEAST AS BIG AS TERM_COLS
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE done
        GET TO THE CHOPPER i
        HERE IS MY INVITATION TERM_COLS
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
CHILL
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termWritePrompt
DO IT NOW termPutChar 0x41
DO IT NOW termPutChar 0x52
DO IT NOW termPutChar 0x4E
DO IT NOW termPutChar 0x4F
DO IT NOW termPutChar 0x4C
DO IT NOW termPutChar 0x44
DO IT NOW termPutChar 0x2D
DO IT NOW termPutChar 0x4F
DO IT NOW termPutChar 0x53
DO IT NOW termPutChar 0x3E
DO IT NOW termPutChar 0x20
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termScrollUp
HEY CHRISTMAS TREE y
THIS IS A WARRIOR
YOU SET US UP 1
STICK AROUND y
    HEY CHRISTMAS TREE x
    THIS IS A WARRIOR
    YOU SET US UP 0
    STICK AROUND x
        HEY CHRISTMAS TREE src
        THIS IS A WARRIOR
        YOU SET US UP 0
        HEY CHRISTMAS TREE dst
        THIS IS A WARRIOR
        YOU SET US UP 0
        GET TO THE CHOPPER src
        HERE IS MY INVITATION y
        YOU'RE FIRED TERM_COLS
        GET UP x
        ENOUGH TALK
        GET TO THE CHOPPER dst
        HERE IS MY INVITATION y
        GET DOWN 1
        YOU'RE FIRED TERM_COLS
        GET UP x
        ENOUGH TALK
        GET TO THE CHOPPER WHICH ONE termBuffer dst
        HERE IS MY INVITATION WHICH ONE termBuffer src
        ENOUGH TALK
        GET TO THE CHOPPER x
        HERE IS MY INVITATION x
        GET UP 1
        ENOUGH TALK
        HEY CHRISTMAS TREE doneX
        THIS IS A WARRIOR
        YOU SET US UP 0
        GET TO THE CHOPPER doneX
        HERE IS MY INVITATION x
        YOU'RE AT LEAST AS BIG AS TERM_COLS
        ENOUGH TALK
        BECAUSE I'M GOING TO SAY PLEASE doneX
            GET TO THE CHOPPER x
            HERE IS MY INVITATION TERM_COLS
            ENOUGH TALK
        YOU HAVE NO RESPECT FOR LOGIC
    CHILL
    GET TO THE CHOPPER y
    HERE IS MY INVITATION y
    GET UP 1
    ENOUGH TALK
    HEY CHRISTMAS TREE doneY
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER doneY
    HERE IS MY INVITATION y
    YOU'RE AT LEAST AS BIG AS TERM_ROWS
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE doneY
        GET TO THE CHOPPER y
        HERE IS MY INVITATION TERM_ROWS
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
CHILL
DO IT NOW termClearLine 24
GET TO THE CHOPPER dirtyLine
HERE IS MY INVITATION -2
ENOUGH TALK
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termDrawLine
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE fbAddr
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE fbPitch
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE lineIndex
HEY CHRISTMAS TREE y
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER y
HERE IS MY INVITATION lineIndex
YOU'RE FIRED CHAR_H
ENOUGH TALK
DO IT NOW fillRect fbAddr fbPitch 0 y TERM_WIDTH_PX CHAR_H TERM_BG
HEY CHRISTMAS TREE x
THIS IS A WARRIOR
YOU SET US UP 0
STICK AROUND x
    HEY CHRISTMAS TREE idx
    THIS IS A WARRIOR
    YOU SET US UP 0
    HEY CHRISTMAS TREE ch
    THIS IS A WARRIOR
    YOU SET US UP 0
    HEY CHRISTMAS TREE px
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER idx
    HERE IS MY INVITATION lineIndex
    YOU'RE FIRED TERM_COLS
    GET UP x
    ENOUGH TALK
    GET TO THE CHOPPER ch
    HERE IS MY INVITATION WHICH ONE termBuffer idx
    ENOUGH TALK
    GET TO THE CHOPPER px
    HERE IS MY INVITATION x
    YOU'RE FIRED CHAR_W
    ENOUGH TALK
    DO IT NOW drawChar fbAddr fbPitch px y ch TERM_FG TERM_BG
    GET TO THE CHOPPER x
    HERE IS MY INVITATION x
    GET UP 1
    ENOUGH TALK
    HEY CHRISTMAS TREE doneX
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER doneX
    HERE IS MY INVITATION x
    YOU'RE AT LEAST AS BIG AS TERM_COLS
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE doneX
        GET TO THE CHOPPER x
        HERE IS MY INVITATION TERM_COLS
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
CHILL
HEY CHRISTMAS TREE isCursorLine
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER isCursorLine
HERE IS MY INVITATION lineIndex
YOU ARE NOT YOU YOU ARE ME cursorY
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE isCursorLine
    BECAUSE I'M GOING TO SAY PLEASE cursorBlink
        HEY CHRISTMAS TREE cx
        THIS IS A WARRIOR
        YOU SET US UP 0
        GET TO THE CHOPPER cx
        HERE IS MY INVITATION cursorX
        YOU'RE FIRED CHAR_W
        ENOUGH TALK
        DO IT NOW fillRect fbAddr fbPitch cx y CHAR_W CHAR_H TERM_FG
    YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE NO RESPECT FOR LOGIC
HASTA LA VISTA, BABY

TALK TO YOURSELF "============================================================================"
TALK TO YOURSELF "  TERMINAL API"
TALK TO YOURSELF "============================================================================"

LISTEN TO ME VERY CAREFULLY initTerminal
HEY CHRISTMAS TREE i
THIS IS A WARRIOR
YOU SET US UP 0
STICK AROUND i
    GET TO THE CHOPPER WHICH ONE termBuffer i
    HERE IS MY INVITATION 0x20
    ENOUGH TALK
    GET TO THE CHOPPER i
    HERE IS MY INVITATION i
    GET UP 1
    ENOUGH TALK
    HEY CHRISTMAS TREE done
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER done
    HERE IS MY INVITATION i
    YOU'RE AT LEAST AS BIG AS TERM_SIZE
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE done
        GET TO THE CHOPPER i
        HERE IS MY INVITATION TERM_SIZE
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
CHILL
GET TO THE CHOPPER cursorX
HERE IS MY INVITATION 0
ENOUGH TALK
GET TO THE CHOPPER cursorY
HERE IS MY INVITATION 0
ENOUGH TALK
GET TO THE CHOPPER scrollOffset
HERE IS MY INVITATION 0
ENOUGH TALK
GET TO THE CHOPPER dirtyLine
HERE IS MY INVITATION -2
ENOUGH TALK
GET TO THE CHOPPER cursorBlink
HERE IS MY INVITATION 1
ENOUGH TALK
DO IT NOW termWritePrompt
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termPutChar
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE charCode
HEY CHRISTMAS TREE isNewline
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER isNewline
HERE IS MY INVITATION charCode
YOU ARE NOT YOU YOU ARE ME 10
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE isNewline
    GET TO THE CHOPPER cursorX
    HERE IS MY INVITATION 0
    ENOUGH TALK
    GET TO THE CHOPPER cursorY
    HERE IS MY INVITATION cursorY
    GET UP 1
    ENOUGH TALK
BULLSHIT
    HEY CHRISTMAS TREE idx
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER idx
    HERE IS MY INVITATION cursorY
    YOU'RE FIRED TERM_COLS
    GET UP cursorX
    ENOUGH TALK
    GET TO THE CHOPPER WHICH ONE termBuffer idx
    HERE IS MY INVITATION charCode
    ENOUGH TALK
    GET TO THE CHOPPER cursorX
    HERE IS MY INVITATION cursorX
    GET UP 1
    ENOUGH TALK
    HEY CHRISTMAS TREE wrap
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER wrap
    HERE IS MY INVITATION cursorX
    YOU'RE AT LEAST AS BIG AS TERM_COLS
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE wrap
        GET TO THE CHOPPER cursorX
        HERE IS MY INVITATION 0
        ENOUGH TALK
        GET TO THE CHOPPER cursorY
        HERE IS MY INVITATION cursorY
        GET UP 1
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE NO RESPECT FOR LOGIC
HEY CHRISTMAS TREE needScroll
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER needScroll
HERE IS MY INVITATION cursorY
YOU'RE AT LEAST AS BIG AS TERM_ROWS
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE needScroll
    DO IT NOW termScrollUp
    GET TO THE CHOPPER cursorY
    HERE IS MY INVITATION TERM_ROWS
    GET DOWN 1
    ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
GET TO THE CHOPPER dirtyLine
HERE IS MY INVITATION cursorY
ENOUGH TALK
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termHandleEnter
DO IT NOW termClearLine cursorY
GET TO THE CHOPPER cursorX
HERE IS MY INVITATION 0
ENOUGH TALK
GET TO THE CHOPPER cursorY
HERE IS MY INVITATION cursorY
GET UP 1
ENOUGH TALK
HEY CHRISTMAS TREE needScroll
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER needScroll
HERE IS MY INVITATION cursorY
YOU'RE AT LEAST AS BIG AS TERM_ROWS
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE needScroll
    DO IT NOW termScrollUp
    GET TO THE CHOPPER cursorY
    HERE IS MY INVITATION TERM_ROWS
    GET DOWN 1
    ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
DO IT NOW termWritePrompt
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termHandleBackspace
HEY CHRISTMAS TREE canBack
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER canBack
HERE IS MY INVITATION cursorX
YOU ARE NOT YOU YOU ARE ME 0
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE canBack
    GET TO THE CHOPPER cursorX
    HERE IS MY INVITATION cursorX
    GET DOWN 1
    ENOUGH TALK
BULLSHIT
    HEY CHRISTMAS TREE canUp
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER canUp
    HERE IS MY INVITATION cursorY
    YOU ARE NOT YOU YOU ARE ME 0
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE canUp
        GET TO THE CHOPPER cursorY
        HERE IS MY INVITATION cursorY
        GET DOWN 1
        ENOUGH TALK
        GET TO THE CHOPPER cursorX
        HERE IS MY INVITATION TERM_COLS
        GET DOWN 1
        ENOUGH TALK
    YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE NO RESPECT FOR LOGIC
HEY CHRISTMAS TREE idx
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER idx
HERE IS MY INVITATION cursorY
YOU'RE FIRED TERM_COLS
GET UP cursorX
ENOUGH TALK
GET TO THE CHOPPER WHICH ONE termBuffer idx
HERE IS MY INVITATION 0x20
ENOUGH TALK
GET TO THE CHOPPER dirtyLine
HERE IS MY INVITATION cursorY
ENOUGH TALK
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY termHandleKey
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE scancode
HEY CHRISTMAS TREE isEnter
THIS IS A WARRIOR
YOU SET US UP 0
GET TO THE CHOPPER isEnter
HERE IS MY INVITATION scancode
YOU ARE NOT YOU YOU ARE ME 0x1C
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE isEnter
    DO IT NOW termHandleEnter
BULLSHIT
    HEY CHRISTMAS TREE isBack
    THIS IS A WARRIOR
    YOU SET US UP 0
    GET TO THE CHOPPER isBack
    HERE IS MY INVITATION scancode
    YOU ARE NOT YOU YOU ARE ME 0x0E
    ENOUGH TALK
    BECAUSE I'M GOING TO SAY PLEASE isBack
        DO IT NOW termHandleBackspace
    BULLSHIT
        HEY CHRISTMAS TREE ascii
        THIS IS A WARRIOR
        YOU SET US UP 0
        HEY CHRISTMAS TREE isMapped
        THIS IS A WARRIOR
        YOU SET US UP 0
        GET TO THE CHOPPER ascii
        HERE IS MY INVITATION 0
        ENOUGH TALK
        GET TO THE CHOPPER isMapped
        HERE IS MY INVITATION 0
        ENOUGH TALK
{map_block}
HASTA LA VISTA, BABY

LISTEN TO ME VERY CAREFULLY drawTerminal
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE fbAddr
I NEED YOUR CLOTHES YOUR BOOTS AND YOUR MOTORCYCLE fbPitch
HEY CHRISTMAS TREE line\nTHIS IS A WARRIOR\nYOU SET US UP 0\nHEY CHRISTMAS TREE doAll\nTHIS IS A WARRIOR\nYOU SET US UP 0\nGET TO THE CHOPPER doAll\nHERE IS MY INVITATION dirtyLine\nYOU ARE NOT YOU YOU ARE ME -2\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE doAll\n    GET TO THE CHOPPER line\n    HERE IS MY INVITATION 0\n    ENOUGH TALK\n    STICK AROUND line\n        DO IT NOW termDrawLine fbAddr fbPitch line\n        GET TO THE CHOPPER line\n        HERE IS MY INVITATION line\n        GET UP 1\n        ENOUGH TALK\n        HEY CHRISTMAS TREE done\n        THIS IS A WARRIOR\n        YOU SET US UP 0\n        GET TO THE CHOPPER done\n        HERE IS MY INVITATION line\n        YOU'RE AT LEAST AS BIG AS TERM_ROWS\n        ENOUGH TALK\n        BECAUSE I'M GOING TO SAY PLEASE done\n            GET TO THE CHOPPER line\n            HERE IS MY INVITATION TERM_ROWS\n            ENOUGH TALK\n        YOU HAVE NO RESPECT FOR LOGIC\n    CHILL\nBULLSHIT\n    HEY CHRISTMAS TREE doOne\n    THIS IS A WARRIOR\n    YOU SET US UP 0\n    GET TO THE CHOPPER doOne\n    HERE IS MY INVITATION dirtyLine\n    YOU'RE AT LEAST AS BIG AS 0\n    ENOUGH TALK\n    BECAUSE I'M GOING TO SAY PLEASE doOne\n        DO IT NOW termDrawLine fbAddr fbPitch dirtyLine\n    YOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE NO RESPECT FOR LOGIC\nHEY CHRISTMAS TREE blinkOn\nTHIS IS A WARRIOR\nYOU SET US UP 0\nGET TO THE CHOPPER blinkOn\nHERE IS MY INVITATION cursorBlink\nYOU ARE NOT YOU YOU ARE ME 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE blinkOn\n    GET TO THE CHOPPER cursorBlink\n    HERE IS MY INVITATION 0\n    ENOUGH TALK\nBULLSHIT\n    GET TO THE CHOPPER cursorBlink\n    HERE IS MY INVITATION 1\n    ENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\nGET TO THE CHOPPER dirtyLine\nHERE IS MY INVITATION cursorY\nENOUGH TALK\nHASTA LA VISTA, BABY\n'''

open(r"C:\\Users\\Acer\\Desktop\\ToaruOS-Arnold\\kernel\\terminal.arnoldc","w",encoding="utf-8").write(content)
